services:
  - type: web
    name: ingle-dsp-react
    runtime: node
    plan: free
    rootDir: ingle-dsp-react
    buildCommand: npm install && npm run build:prod
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
