services:
  - type: web
    name: ingle-dsp-react
    env: static
    buildCommand: cd ingle-dsp-react && npm install && npm run build:prod
    staticPublishPath: ingle-dsp-react/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
